<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authorization code is required' => '',
    'Bạn vui lòng nhập dữ liệu cho trường này' => '',
    'CSRF token is invalid' => '',
    'CSRF token is required' => '',
    'Chọn danh mục' => '',
    'Chọn quận/huyện/thành phố' => '',
    'Chọn sản phẩm' => '',
    'Chọn tỉnh' => '',
    'Client id and Client secret is required' => '',
    'Cần bán' => '',
    'Cần mua' => '',
    'Dữ liệu bạn nhập không hợp lệ' => '',
    'Dữ liệu bạn nhập vượt quá ' => '',
    'Email' => '',
    'Giá' => '',
    'Giá cả thị trường' => '',
    'Gió' => '',
    'Hôm nay' => '',
    'Hệ thống đang bận, vui lòng thử lại sau.' => '',
    'Invalid authorization code' => '',
    'Invalid username password' => '',
    'LG.MƯA' => '',
    'Liên hệ' => '',
    'Loại' => '',
    'Lưu thành công! Bạn sẽ nhận được email khi tin đăng của bạn được phê duyệt trên hệ thống' => '',
    'Lượng mưa' => '',
    'Mua & Bán' => '',
    'Mật độ mây' => '',
    'Mực thủy triều' => '',
    'NH.ĐỘ' => '',
    'Ng' => '',
    'Ngày bắt đầu không được lớn hơn ngày kết thúc' => '',
    'Ngày kia' => '',
    'Ngày mai' => '',
    'Require login.' => '',
    'Successful' => '',
    'Thông tin cơ bản' => '',
    'Thông tin liên hệ' => '',
    'Thời gian' => '',
    'Thời tiết' => '',
    'Tin tức' => '',
    'Tại' => '',
    'Tất cả' => '',
    'Unknown Error' => '',
    'Unknown method' => '',
    'Username and Password is required' => '',
    'Video' => '',
    'Wrong client id and client secret' => '',
    'You are not authorized to perform this action' => '',
    'Your account is locked' => '',
    'Your account is not active' => '',
    'Áp xuất' => '',
    'Điện thoại' => '',
    'Đăng tin' => '',
    'Địa chỉ' => '',
    'Độ ẩm' => '',
    'Ảnh bạn đưa lên server bị lỗi.' => '',
];
